;;;; EURISKO LLM Integration - Redesigned for Symbolic Integration
;;;; Enhanced heuristics that bridge LLM insights with EURISKO's symbolic reasoning
;;;; Author: AI Assistant  
;;;; Date: 2025
;;;; Dependencies: drakma (HTTP client), cl-json (JSON handling)
;;;;
;;;; DESIGN PHILOSOPHY:
;;;; Instead of generating opaque text, LLM heuristics now:
;;;; 1. Generate structured symbolic knowledge EURISKO can manipulate
;;;; 2. Create new concepts, slots, and relationships
;;;; 3. Suggest concrete modifications to existing units
;;;; 4. Provide guidance that integrates with EURISKO's reasoning mechanisms
;;;;
;;;; KEY IMPROVEMENTS:
;;;; - LLM outputs are parsed into EURISKO's symbolic structures
;;;; - Generated insights become new concepts/slots/rules
;;;; - Failure analysis creates concrete avoidance heuristics
;;;; - Pattern recognition generates new mathematical concepts
;;;; - All LLM guidance is actionable within EURISKO's framework

(in-package "EURISCLO")

;; Load required libraries for HTTP requests and JSON
(eval-when (:compile-toplevel :load-toplevel :execute)
  (handler-case
      (progn
        (ql:quickload :drakma :silent t)
        (ql:quickload :cl-json :silent t))
    (error (e)
      (format t "Warning: Could not load HTTP dependencies: ~A~%" e)
      (format t "Install with: (ql:quickload '(:drakma :cl-json))~%")
      (format t "Will use mock responses only.~%"))))

;;; =============================================================================
;;; SHARED HEURISTIC VARIABLES
;;; =============================================================================

;; Declare variables that are defined in heuristics.lisp but needed here
(defvar *old-value*)
(defvar *new-value*)
(defvar *slot-to-change*)
(defvar *new-units*)
(defvar *creditors*)
(defvar *conjectures*)
(defvar *all-units*)
(defvar *deleted-units*)
(defvar *task-num*)
(defvar *task*)
(defvar *abort-task?*)

;; LLM-specific variables
(defvar *llm-generated-concepts* nil "List of concepts generated by LLM")
(defvar *llm-generated-slots* nil "List of slots generated by LLM")
(defvar *llm-suggested-rules* nil "List of rules suggested by LLM")

;;; =============================================================================
;;; LLM INFRASTRUCTURE (Fixed)
;;; =============================================================================

;;; LLM Provider Configuration
(defvar *llm-provider* :ollama
  "Current LLM provider. Supported: :gemini, :openai, :claude, :ollama")

(defvar *llm-api-key* nil
  "API key for the current LLM provider")

(defvar *llm-model* "qwen2.5:14b"
  "Model name for the current provider")

(defvar *llm-temperature* 0.7
  "Temperature setting for LLM responses")

(defvar *llm-max-tokens* 2048
  "Maximum tokens for LLM responses")

(defvar *llm-timeout* 30
  "Timeout for LLM API calls in seconds")

;;; LLM Provider Configurations
(defparameter *llm-providers*
  '((:gemini 
     :base-url "https://generativelanguage.googleapis.com/v1beta/models/"
     :headers (("Content-Type" . "application/json"))
     :auth-header "x-goog-api-key"
     :request-format :gemini)
    (:openai
     :base-url "https://api.openai.com/v1/chat/completions"
     :headers (("Content-Type" . "application/json"))
     :auth-header "Authorization"
     :auth-prefix "Bearer "
     :request-format :openai)
    (:claude
     :base-url "https://api.anthropic.com/v1/messages"
     :headers (("Content-Type" . "application/json")
               ("anthropic-version" . "2023-06-01"))
     :auth-header "x-api-key"
     :request-format :claude)
    (:ollama
     :base-url "http://localhost:11434/api/generate"
     :headers (("Content-Type" . "application/json"))
     :request-format :ollama)))

;;; =============================================================================
;;; LLM INTERFACE FUNCTIONS (Fixed)
;;; =============================================================================

(defun get-provider-config (provider)
  "Get configuration for the specified LLM provider"
  (cdr (assoc provider *llm-providers*)))

(defun escape-json-string (str)
  "Escape a string for JSON"
  (with-output-to-string (out)
    (loop for char across str do
      (case char
        (#\" (write-string "\\\"" out))
        (#\\ (write-string "\\\\" out))
        (#\Newline (write-string "\\n" out))
        (#\Return (write-string "\\r" out))
        (#\Tab (write-string "\\t" out))
        (otherwise (write-char char out))))))

(defun eurisko-llm-api-call (prompt &key provider model temperature max-tokens)
  "Make HTTP request to LLM API - fixed version with proper JSON escaping"
  (let* ((provider (or provider *llm-provider*))
         (model (or model *llm-model*))
         (config (get-provider-config provider))
         (base-url (getf config :base-url))
         (api-key *llm-api-key*))
    
    (handler-case
        (case provider
          (:gemini
           (if (and api-key (stringp api-key) (not (string= api-key "")))
               (let* ((json-string (format nil "{\"contents\":[{\"parts\":[{\"text\":\"~A\"}]}],\"generationConfig\":{\"temperature\":~A,\"maxOutputTokens\":~A}}" 
                                          (escape-json-string prompt)
                                          (or temperature *llm-temperature*)
                                          (or max-tokens *llm-max-tokens*)))
                      (full-url (format nil "~A~A:generateContent?key=~A" base-url model api-key)))
                 (multiple-value-bind (response status-code)
                     (drakma:http-request full-url
                                        :method :post
                                        :content-type "application/json"
                                        :content json-string
                                        :want-stream nil)
                   (if (= status-code 200)
                       (let ((response-string (if (stringp response)
                                                  response
                                                  (map 'string #'code-char response))))
                         (cl-json:decode-json-from-string response-string))
                       (format nil "API Error: Status ~A" status-code))))
               (format nil "Mock Gemini response - no API key")))
          
          (:ollama
           ;; Ollama doesn't need an API key - escape the prompt for JSON
           (let* ((json-string (format nil "{\"model\":\"~A\",\"prompt\":\"~A\",\"stream\":false,\"options\":{\"temperature\":~A}}" 
                                      model (escape-json-string prompt) (or temperature *llm-temperature*)))
                  (full-url base-url))
             (multiple-value-bind (response status-code)
                 (drakma:http-request full-url
                                    :method :post
                                    :content-type "application/json"
                                    :content json-string
                                    :want-stream nil)
               (if (= status-code 200)
                   (let ((response-string (if (stringp response)
                                              response
                                              (map 'string #'code-char response))))
                     (cl-json:decode-json-from-string response-string))
                   (format nil "Ollama Error: Status ~A" status-code)))))
          
          (:openai
           (format nil "OpenAI not implemented yet"))
          
          (otherwise
           (format nil "Provider ~A not implemented" provider)))
      (error (e)
        (format nil "Error calling LLM: ~A" e)))))

(defun extract-llm-response (response provider)
  "Extract text content from LLM response based on provider format"
  (cond
    ;; If it's already a string (mock response), return as-is
    ((stringp response) response)
    
    ;; Handle real API responses
    ((listp response)
     (case provider
       (:gemini
        ;; Navigate: CANDIDATES -> first item -> CONTENT -> PARTS -> first item -> TEXT
        (let* ((candidates (cdr (assoc :candidates response)))
               (first-candidate (first candidates))
               (content (cdr (assoc :content first-candidate)))
               (parts (cdr (assoc :parts content)))
               (first-part (first parts))
               (text (cdr (assoc :text first-part))))
          text))
       (:ollama
        ;; Ollama returns response in :RESPONSE field (keyword)
        (cdr (assoc :response response)))
       (:openai
        (let* ((choices (cdr (assoc :choices response)))
               (first-choice (first choices))
               (message (cdr (assoc :message first-choice)))
               (content (cdr (assoc :content message))))
          content))
       (:claude
        (let* ((content (cdr (assoc :content response)))
               (first-content (first content))
               (text (cdr (assoc :text first-content))))
          text))
       (otherwise
        (format nil "Unknown provider: ~A" provider))))
    
    ;; Fallback
    (t (format nil "~A" response))))

(defun llm-query (prompt &key provider model temperature max-tokens context)
  "High-level interface for LLM queries"
  (let* ((full-prompt (if context
                         (format nil "Context: ~A~%~%Query: ~A" context prompt)
                         prompt))
         (response (eurisko-llm-api-call full-prompt 
                                        :provider provider 
                                        :model model 
                                        :temperature temperature 
                                        :max-tokens max-tokens)))
    
    (when response
      (let ((text (extract-llm-response response (or provider *llm-provider*))))
        ;; Ensure we always return a string
        (unless (stringp text)
          (setf text (format nil "~A" text)))
        text))))

;;; =============================================================================
;;; STRUCTURED LLM OUTPUT PARSERS
;;; =============================================================================

(defun parse-llm-concept-definition (response)
  "Parse LLM response into structured concept definition"
  (when (and response (stringp response))
    (let ((lines (split-string response #\Newline))
          (concept-def '()))
      (dolist (line lines)
        (let ((trimmed (string-trim '(#\Space #\Tab) line)))
          (cond
            ((search "NAME:" trimmed)
             (push (cons 'name (string-trim '(#\Space) (subseq trimmed 5))) concept-def))
            ((search "ISA:" trimmed)
             (push (cons 'isa (intern (string-upcase (string-trim '(#\Space) (subseq trimmed 4))))) concept-def))
            ((search "ENGLISH:" trimmed)
             (push (cons 'english (string-trim '(#\Space) (subseq trimmed 8))) concept-def))
            ((search "DOMAIN:" trimmed)
             (push (cons 'domain (intern (string-upcase (string-trim '(#\Space) (subseq trimmed 7))))) concept-def))
            ((search "WORTH:" trimmed)
             (let ((worth-str (string-trim '(#\Space) (subseq trimmed 6))))
               (push (cons 'worth (parse-integer worth-str :junk-allowed t)) concept-def))))))
      (when concept-def (nreverse concept-def)))))

(defun parse-llm-slot-suggestion (response)
  "Parse LLM response into structured slot suggestion"
  (when (and response (stringp response))
    (let ((lines (split-string response #\Newline))
          (slot-def '()))
      (dolist (line lines)
        (let ((trimmed (string-trim '(#\Space #\Tab) line)))
          (cond
            ((search "SLOT:" trimmed)
             (push (cons 'slot (intern (string-upcase (string-trim '(#\Space) (subseq trimmed 5))))) slot-def))
            ((search "VALUE:" trimmed)
             (push (cons 'value (string-trim '(#\Space) (subseq trimmed 6))) slot-def))
            ((search "REASON:" trimmed)
             (push (cons 'reason (string-trim '(#\Space) (subseq trimmed 7))) slot-def)))))
      (when slot-def (nreverse slot-def)))))

(defun parse-llm-rule (response)
  "Parse LLM response into structured rule"
  (when (and response (stringp response))
    (let ((if-pos (search "IF:" response))
          (then-pos (search "THEN:" response))
          (worth-pos (search "WORTH:" response)))
      (when (and if-pos then-pos)
        `((condition . ,(string-trim '(#\Space #\Newline) 
                                   (subseq response (+ if-pos 3) then-pos)))
          (action . ,(string-trim '(#\Space #\Newline)
                                (subseq response (+ then-pos 5) 
                                       (or worth-pos (length response)))))
          (worth . ,(when worth-pos
                     (parse-integer (string-trim '(#\Space #\Newline)
                                               (subseq response (+ worth-pos 6)))
                                   :junk-allowed t))))))))

(defun split-string (string delimiter)
  "Simple string splitting utility"
  (let ((result '())
        (start 0))
    (loop for pos = (position delimiter string :start start)
          do (push (subseq string start pos) result)
             (if pos
                 (setf start (1+ pos))
                 (return (nreverse result))))))

;;; =============================================================================
;;; SYMBOLIC INTEGRATION UTILITIES
;;; =============================================================================

(defvar *unit-failure-counts* (make-hash-table)
  "Track how many times each unit has failed operations")

(defun count-failures-for-unit (unit)
  "Count how many times a unit has failed operations"
  (gethash unit *unit-failure-counts* 0))

(defun record-failure-for-unit (unit)
  "Record a failure for a unit"
  (setf (gethash unit *unit-failure-counts*)
        (1+ (gethash unit *unit-failure-counts* 0))))

(defun implement-llm-rule (rule-def)
  "Convert an LLM-generated rule into a working EURISKO heuristic"
  (when rule-def
    (let* ((rule-name (cdr (assoc 'name rule-def)))
           (condition-text (cdr (assoc 'condition rule-def)))
           (action-text (cdr (assoc 'action rule-def)))
           (worth (or (cdr (assoc 'worth rule-def)) 400)))
      
      (when (and rule-name condition-text action-text)
        (cprin1 40 "Implementing LLM rule: " rule-name "~%")
        
        ;; For now, create a simple avoidance heuristic
        ;; In a full implementation, you'd parse condition-text into actual Lisp predicates
        (eval 
         `(defheuristic ,rule-name
            isa (heuristic op anything)
            english ,(format nil "LLM-Generated: ~A" action-text)
            if-potentially-relevant (lambda (f)
                                      ;; Simple heuristic: avoid if unit has failed before
                                      (> (count-failures-for-unit f) 1))
            worth ,worth
            abbrev ,(format nil "LLM: ~A" (subseq action-text 0 (min 50 (length action-text))))
            then-compute (lambda (f)
                           (cprin1 15 "LLM rule " ',rule-name " preventing operation on " f "~%")
                           nil) ; Return nil to prevent the operation
            arity 1))
        
        ;; Register the new heuristic
        (when (fboundp 'union-prop)
          (union-prop 'heuristic 'examples rule-name))
        
        (cprin1 15 "Successfully implemented heuristic: " rule-name "~%")
        t))))

(defun create-concept-from-llm (concept-def)
  "Create a EURISKO concept from LLM-generated definition"
  (when concept-def
    (let* ((name-str (cdr (assoc 'name concept-def)))
           (concept-name (when name-str (intern (string-upcase name-str)))))
      (when concept-name
        (cprin1 40 "Creating LLM-generated concept: " concept-name "~%")
        ;; Create the unit
        (create-unit concept-name concept-name)
        ;; Set properties from LLM definition
        (dolist (prop concept-def)
          (case (car prop)
            (isa (put concept-name 'isa (cdr prop)))
            (english (put concept-name 'english (cdr prop)))
            (domain (put concept-name 'domain (cdr prop)))
            (worth (put concept-name 'worth (cdr prop)))))
        ;; Mark as LLM-generated
        (put concept-name 'creditors '(llm-generated))
        (push concept-name *llm-generated-concepts*)
        concept-name))))

(defun add-slot-from-llm (unit slot-def)
  "Add a slot to a unit based on LLM suggestion"
  (when (and unit slot-def)
    (let ((slot-name (cdr (assoc 'slot slot-def)))
          (slot-value-text (cdr (assoc 'value slot-def)))
          (reason (cdr (assoc 'reason slot-def))))
      (when (and slot-name slot-value-text)
        (cprin1 40 "Adding LLM-suggested slot " slot-name " to " unit "~%")
        
        ;; Convert text to appropriate EURISKO value
        (let ((slot-value (convert-text-to-slot-value slot-value-text slot-name)))
          (when slot-value
            (put unit slot-name slot-value)
            (when reason
              (put unit (intern (format nil "~A-REASON" slot-name)) reason))
            (push (list unit slot-name slot-value) *llm-generated-slots*)
            (cprin1 40 "Successfully added slot " slot-name " with value " slot-value "~%")
            t))))))

(defun convert-text-to-slot-value (text slot-name)
  "Convert LLM text to appropriate EURISKO slot value"
  (when (stringp text)
    (let ((trimmed (string-trim '(#\Space #\Tab #\Newline) text)))
      (cond
        ;; Empty string
        ((= (length trimmed) 0) nil)
        
        ;; For WORTH slot, ensure we get a number
        ((let ((slot-name-str (cond ((symbolp slot-name) (symbol-name slot-name))
                                   ((stringp slot-name) (string-upcase slot-name))
                                   (t (format nil "~A" slot-name)))))
           (string= slot-name-str "WORTH"))
         (let ((parsed-number (parse-integer trimmed :junk-allowed t)))
           (if parsed-number
               parsed-number
               (progn
                 (cprin1 40 "Warning: Non-numeric WORTH value '" trimmed "', defaulting to 400~%")
                 400))))
        
        ;; Special handling for slots that EURISKO expects as lists
        ((let ((slot-name-str (cond ((symbolp slot-name) (symbol-name slot-name))
                                   ((stringp slot-name) (string-upcase slot-name))
                                   (t (format nil "~A" slot-name)))))
           (some (lambda (expected-slot) (string= slot-name-str expected-slot))
                 '("DOMAIN" "ISA" "EXAMPLES" "SPECIALIZATIONS" "GENERALIZATIONS" 
                   "APPLICS-OF" "APPLICS-TO" "APPLICS-WITH" "SUPERIORS" "SUBORDINATES")))
         ;; Convert to a list containing the symbol
         (let ((symbol-value (if (and (> (length trimmed) 0)
                                     (alpha-char-p (char trimmed 0))
                                     (every (lambda (c) (or (alphanumericp c) (char= c #\-))) trimmed)
                                     (< (length trimmed) 30))
                               (intern (string-upcase trimmed))
                               trimmed)))
           (list symbol-value)))
        
        ;; If it looks like a pure number, parse it
        ((every (lambda (c) (or (digit-char-p c) (char= c #\.) (char= c #\-))) trimmed)
         (or (parse-integer trimmed :junk-allowed t)
             (parse-float trimmed :junk-allowed t)
             trimmed))
        
        ;; If it's trying to be a list or function, be very careful
        ((and (> (length trimmed) 0)
              (or (char= (char trimmed 0) #\()
                  (search "lambda" trimmed)
                  (search "IF " trimmed)
                  (search "THEN " trimmed)))
         ;; For now, don't try to evaluate LLM-generated code
         ;; Store as text with a warning
         (cprin1 40 "Warning: LLM generated code-like text for " slot-name ", storing as description~%")
         (format nil "LLM-Description: ~A" trimmed))
        
        ;; If it looks like a simple concept name, try to intern it
        ((and (> (length trimmed) 0)
              (alpha-char-p (char trimmed 0))
              (every (lambda (c) (or (alphanumericp c) (char= c #\-))) trimmed)
              (< (length trimmed) 30)) ; Reasonable concept name length
         (intern (string-upcase trimmed)))
        
        ;; Default: store as text for safety
        (t trimmed)))))


(defun parse-float (string &key (junk-allowed nil))
  "Simple float parser"
  (handler-case
      (let ((*read-eval* nil))
        (read-from-string string nil nil))
    (error () 
      (if junk-allowed nil (error "Not a valid float")))))


(defun create-avoidance-rule-from-llm (rule-def context)
  "Create an avoidance heuristic from LLM-generated rule"
  (when rule-def
    (let* ((condition (cdr (assoc 'condition rule-def)))
           (action (cdr (assoc 'action rule-def)))
           (worth (or (cdr (assoc 'worth rule-def)) 300))
           (rule-name (intern (format nil "H-LLM-AVOID-~A" (length *llm-suggested-rules*)))))
      (when (and condition action)
        (cprin1 40 "Creating LLM-generated avoidance rule: " rule-name "~%")
        ;; Store the rule for potential implementation
        (push `((name . ,rule-name)
                (condition . ,condition)
                (action . ,action)
                (worth . ,worth)
                (context . ,context)) *llm-suggested-rules*)
        rule-name))))

;;; =============================================================================
;;; REDESIGNED LLM-ENHANCED HEURISTICS
;;; =============================================================================

(defheuristic h30-llm-concept-generator
  isa (heuristic op anything)
  english "IF we've seen patterns in successful concepts, THEN use LLM to generate new related concepts"
  if-potentially-relevant (lambda (f)
                            (declare (ignore f))
                            (and *llm-api-key*
                                 (> (length *conjectures*) 3)))
  worth 850
  abbrev "LLM-guided concept generation from patterns"
  then-compute (lambda (f)
                 (declare (ignore f))
                 (cprin1 40 "H30: Analyzing successful patterns to generate new concepts~%")
                 (let* ((recent-successes (subseq *conjectures* 0 (min 3 (length *conjectures*))))
                        (pattern-context (format nil "Recent successful concepts: ~A" 
                                               (mapcar (lambda (c) 
                                                        (list (english c) (isa c) (domain c))) 
                                                      recent-successes)))
                        (prompt (format nil "Based on these successful mathematical concepts, suggest a new related concept:

~A

Generate a concept definition in this format:
NAME: [concept name]
ISA: [parent concept]  
ENGLISH: [description]
DOMAIN: [domain if applicable]
WORTH: [estimated worth 100-900]

The new concept should be mathematically meaningful and related to the successful patterns."
                                       pattern-context))
                        (response (llm-query prompt :temperature 0.8)))
                   (when response
                     (let ((concept-def (parse-llm-concept-definition response)))
                       (if concept-def
                           (let ((new-concept (create-concept-from-llm concept-def)))
                             (when new-concept
                               (cprin1 15 "LLM generated new concept: " new-concept "~%")
                               (add-task-results 'llm-generated-concept new-concept)
                               t))
                           (progn
                             (cprin1 40 "H30: Failed to parse LLM concept definition~%")
                             nil))))))
  arity 1)

(defheuristic h31-llm-slot-evolver
  isa (heuristic op anything)
  english "IF current task is to modify a unit, THEN use LLM to suggest specific slot modifications"
  if-potentially-relevant null
  worth 800
  abbrev "LLM-guided slot evolution with structured output"
  if-working-on-task (lambda (task)
                       (declare (ignore task))
                       (and *llm-api-key*
                            (or (is-a-kind-of *cur-slot* 'specializations)
                                (is-a-kind-of *cur-slot* 'generalizations))))
  then-compute (lambda (task)
                 (declare (ignore task))
                 (cprin1 40 "H31: Requesting LLM slot modification for " *cur-unit* "~%")
                 (let* ((unit-context (format nil "Unit: ~A, Description: ~A"
                                             *cur-unit*
                                             (or (english *cur-unit*) (abbrev *cur-unit*) "No description")))
                        (operation (if (is-a-kind-of *cur-slot* 'specializations) 
                                      "specialize" "generalize"))
                        (prompt (format nil "Suggest a simple slot modification to ~A this mathematical concept:

~A

Provide suggestion in this format:
SLOT: [simple slot name like WORTH, DOMAIN, or EXAMPLES]
VALUE: [simple value - a number, symbol, or short text - NOT code or complex expressions]
REASON: [brief mathematical justification]

Examples of good values:
- Numbers: 750, 0.5
- Symbols: MATH-OP, PRIME-NUM  
- Short text: \"operations on integers\"

Do NOT suggest complex code, functions, or long descriptions as values."
                                       operation unit-context))
                        (response (llm-query prompt :temperature 0.5)))
                   (when response
                     (let ((slot-suggestion (parse-llm-slot-suggestion response)))
                       (if (and slot-suggestion (add-slot-from-llm *cur-unit* slot-suggestion))
                           (progn
                             (cprin1 15 "LLM suggested simple slot modification for " *cur-unit* "~%")
                             (add-task-results 'llm-slot-modification slot-suggestion)
                             t)
                           (progn
                             (cprin1 40 "H31: Failed to apply LLM slot suggestion~%")
                             nil))))))
  arity 1)

(defheuristic h32-llm-failure-analyzer
  isa (heuristic op anything)
  english "IF a concept repeatedly fails in the same way, THEN use LLM to generate structured avoidance rules"
  if-potentially-relevant null
  worth 750
  abbrev "LLM-powered failure pattern analysis with rule generation"
  if-finished-working-on-task (lambda (task)
                                (declare (ignore task))
                                (and *llm-api-key*
                                     ;; Only trigger for repeated failures, not early exploration
                                     (> *task-num* 50)  ; Allow early exploration
                                     (let ((new-units (cdr (assoc 'new-units *task-results*))))
                                       (and (or (null new-units)
                                               (every (lambda (u) (< (worth u) 200)) new-units))
                                            ;; Check if this unit has failed before
                                            (> (count-failures-for-unit *cur-unit*) 2)))))
  then-compute (lambda (task)
                 (declare (ignore task))
                 (let* ((operation (if (is-a-kind-of *cur-slot* 'specializations) 
                                      "specialization" "generalization"))
                        (failure-context (format nil "Repeated failed ~A of ~A" operation *cur-unit*))
                        (prompt (format nil "This mathematical operation has failed multiple times: ~A

This suggests a systematic issue, not random exploration failure.
Analyze why this type of operation consistently fails and suggest a prevention rule.

Provide in this format:
IF: [condition that indicates when to avoid this type of operation]
THEN: [action to take instead]  
WORTH: [estimated worth of this rule 100-800]

Focus on mathematical principles and structural properties that lead to systematic failure."
                                       failure-context))
                        (response (llm-query prompt :temperature 0.6)))
                   (when response
                     (let ((rule-def (parse-llm-rule response)))
                       (if rule-def
                           (let ((new-rule (create-avoidance-rule-from-llm rule-def failure-context)))
                             (when new-rule
                               (cprin1 15 "LLM generated avoidance rule for repeated failure: " new-rule "~%")
                               (add-task-results 'llm-avoidance-rule new-rule)
                               t))
                           (progn
                             (cprin1 40 "H32: Failed to parse LLM rule~%")
                             nil))))))
  arity 1)

(defheuristic h33-llm-pattern-recognizer
  isa (heuristic op anything)
  english "IF we have multiple examples of a concept, THEN use LLM to identify mathematical patterns"
  if-potentially-relevant (lambda (f)
                            (and *llm-api-key*
                                 (> (length (examples f)) 4)
                                 (memb 'math-concept (isa f))))
  worth 700
  abbrev "LLM-guided pattern recognition and concept refinement"
  then-compute (lambda (f)
                 (cprin1 40 "H33: Analyzing patterns in examples of " f "~%")
                 (let* ((example-list (subseq (examples f) 0 (min 10 (length (examples f)))))
                        (concept-context (format nil "Concept: ~A (~A), Examples: ~A"
                                               f (english f) example-list))
                        (prompt (format nil "Analyze these examples of a mathematical concept:

~A

Identify key mathematical patterns or properties. Suggest either:
1. A new related concept that captures a pattern you see
2. A slot that should be added to better characterize this concept

Format your response as either:
CONCEPT - NAME: [name] ISA: [parent] ENGLISH: [description] WORTH: [worth]
OR  
SLOT - SLOT: [slot name] VALUE: [slot value] REASON: [mathematical justification]"
                                       concept-context))
                        (response (llm-query prompt :temperature 0.7)))
                   (when response
                     (cond
                       ((search "CONCEPT -" response)
                        (let ((concept-def (parse-llm-concept-definition 
                                           (subseq response (+ (search "CONCEPT -" response) 10)))))
                          (when concept-def
                            (let ((new-concept (create-concept-from-llm concept-def)))
                              (when new-concept
                                (cprin1 15 "LLM identified pattern and created: " new-concept "~%")
                                (add-task-results 'llm-pattern-concept new-concept)
                                t)))))
                       ((search "SLOT -" response)
                        (let ((slot-def (parse-llm-slot-suggestion 
                                        (subseq response (+ (search "SLOT -" response) 7)))))
                          (when (and slot-def (add-slot-from-llm f slot-def))
                            (cprin1 15 "LLM identified pattern and added slot to " f "~%")
                            (add-task-results 'llm-pattern-slot slot-def)
                            t)))
                       (t (cprin1 40 "H33: Could not parse LLM pattern analysis~%")
                          nil)))))
  arity 1)

(defheuristic h34-llm-relation-discoverer
  isa (heuristic op anything)
  english "IF we have related concepts, THEN use LLM to discover mathematical relationships"
  if-potentially-relevant (lambda (f)
                            (and *llm-api-key*
                                 (generalizations f)
                                 (specializations f)))
  worth 650
  abbrev "LLM-guided discovery of mathematical relationships"
  then-compute (lambda (f)
                 (cprin1 40 "H34: Discovering relationships for " f "~%")
                 (let* ((genls (subseq (generalizations f) 0 (min 3 (length (generalizations f)))))
                        (specs (subseq (specializations f) 0 (min 3 (length (specializations f)))))
                        (relationship-context (format nil "Concept: ~A, Generalizations: ~A, Specializations: ~A"
                                                     f genls specs))
                        (prompt (format nil "Given this mathematical concept hierarchy:

~A

Suggest a mathematical relationship or property that connects these concepts.

Format:
SLOT: [relationship name]
VALUE: [mathematical relationship or property]
REASON: [why this relationship is mathematically significant]"
                                       relationship-context))
                        (response (llm-query prompt :temperature 0.6)))
                   (when response
                     (let ((relation-def (parse-llm-slot-suggestion response)))
                       (if (and relation-def (add-slot-from-llm f relation-def))
                           (progn
                             (cprin1 15 "LLM discovered relationship for " f "~%")
                             (add-task-results 'llm-relationship relation-def)
                             t)
                           (progn
                             (cprin1 40 "H34: Failed to establish LLM relationship~%")
                             nil))))))
  arity 1)

(defheuristic h35-llm-insight-implementer
  isa (heuristic op anything)
  english "IF we have accumulated LLM insights, THEN convert them into working EURISKO heuristics"
  if-potentially-relevant (lambda (f)
                            (declare (ignore f))
                            (and *llm-api-key*
                                 (> (length *llm-suggested-rules*) 2)
                                 ;; Only run periodically to avoid spam
                                 (= (mod *task-num* 25) 0)))
  worth 600
  abbrev "Automatic implementation of LLM-generated heuristic insights"
  then-compute (lambda (f)
                 (declare (ignore f))
                 (cprin1 40 "H35: Converting LLM insights into working heuristics~%")
                 (let ((implemented-count 0))
                   (dolist (rule-def *llm-suggested-rules*)
                     (when (and rule-def (not (getf rule-def 'implemented)))
                       (let ((success (implement-llm-rule rule-def)))
                         (when success
                           (incf implemented-count)
                           (setf (getf rule-def 'implemented) t)))))
                   (when (> implemented-count 0)
                     (cprin1 15 "H35: Successfully implemented " implemented-count " LLM-generated heuristics~%")
                     (add-task-results 'implemented-heuristics implemented-count)
                     t)))
  arity 1)

;;; =============================================================================
;;; LLM CONFIGURATION AND UTILITIES
;;; =============================================================================

(defun configure-llm (provider &key api-key model temperature max-tokens)
  "Configure LLM settings"
  (setf *llm-provider* provider)
  ;; Only set API key if provided - Ollama doesn't need one
  (when api-key (setf *llm-api-key* api-key))
  (when model (setf *llm-model* model))
  (when temperature (setf *llm-temperature* temperature))
  (when max-tokens (setf *llm-max-tokens* max-tokens))
  (cprin1 13 "Configured LLM: " provider " with model " *llm-model* "~%"))

(defun llm-status ()
  "Display current LLM configuration status"
  (format t "~%LLM Status:~%")
  (format t "Provider: ~A~%" *llm-provider*)
  (format t "Model: ~A~%" *llm-model*)
  (format t "API Key: ~A~%" (if (and *llm-api-key* (not (string= *llm-api-key* ""))) 
                                "Set" 
                                "Not set"))
  (format t "Temperature: ~A~%" *llm-temperature*)
  (format t "Max Tokens: ~A~%" *llm-max-tokens*)
  (format t "Generated Concepts: ~A~%" (length *llm-generated-concepts*))
  (format t "Generated Slots: ~A~%" (length *llm-generated-slots*))
  (format t "Suggested Rules: ~A~%" (length *llm-suggested-rules*)))

(defun reset-llm-data ()
  "Reset LLM-generated data"
  (setf *llm-generated-concepts* nil
        *llm-generated-slots* nil
        *llm-suggested-rules* nil)
  (cprin1 13 "Reset LLM-generated data~%"))

(defun show-llm-insights ()
  "Display insights generated by LLM heuristics"
  (format t "~%=== LLM-Generated Insights ===~%")
  (format t "Concepts: ~A~%" *llm-generated-concepts*)
  (format t "Slots: ~A~%" *llm-generated-slots*)
  (format t "Rules: ~A~%" *llm-suggested-rules*))

;;; =============================================================================
;;; HEURISTIC REGISTRATION
;;; =============================================================================

(defun register-llm-heuristics ()
  "Register LLM heuristics with the EURISKO system"
  (let ((llm-heuristics '(h30-llm-concept-generator 
                         h31-llm-slot-evolver
                         h32-llm-failure-analyzer
                         h33-llm-pattern-recognizer
                         h34-llm-relation-discoverer
                         h35-llm-insight-implementer)))
    
    ;; Add to examples of 'heuristic if that's how EURISKO tracks them
    (when (fboundp 'union-prop)
      (dolist (h llm-heuristics)
        (union-prop 'heuristic 'examples h)))
    
    (format t "Registered ~A LLM heuristics~%" (length llm-heuristics))))

;;; =============================================================================
;;; INITIALIZATION
;;; =============================================================================

(defun initialize-llm-heuristics ()
  "Initialize LLM-enhanced heuristics system"
  (cprin1 13 "~%Initializing LLM-enhanced EURISKO heuristics...~%")
  (cprin1 13 "Added heuristics: H30-H34 (LLM-guided symbolic integration)~%")
  (cprin1 13 "Use (configure-llm :ollama :model \"qwen2.5:14b\") to enable LLM features~%")
  (register-llm-heuristics)
  (llm-status))

;; Auto-initialize when loaded
(initialize-llm-heuristics)
