;;;; EURISKO LLM Integration - Redesigned for Symbolic Integration
;;;; Enhanced heuristics that bridge LLM insights with EURISKO's symbolic reasoning
;;;; Author: AI Assistant  
;;;; Date: 2025
;;;; Dependencies: drakma (HTTP client), cl-json (JSON handling)
;;;;
;;;; DESIGN PHILOSOPHY:
;;;; Instead of generating opaque text, LLM heuristics now:
;;;; 1. Generate structured symbolic knowledge EURISKO can manipulate
;;;; 2. Create new concepts, slots, and relationships
;;;; 3. Suggest concrete modifications to existing units
;;;; 4. Provide guidance that integrates with EURISKO's reasoning mechanisms
;;;;
;;;; KEY IMPROVEMENTS:
;;;; - LLM outputs are parsed into EURISKO's symbolic structures
;;;; - Generated insights become new concepts/slots/rules
;;;; - Failure analysis creates concrete avoidance heuristics
;;;; - Pattern recognition generates new mathematical concepts
;;;; - All LLM guidance is actionable within EURISKO's framework

(in-package "EURISCLO")

;; Load required libraries for HTTP requests and JSON
(eval-when (:compile-toplevel :load-toplevel :execute)
  (handler-case
      (progn
        (ql:quickload :drakma :silent t)
        (ql:quickload :cl-json :silent t))
    (error (e)
      (format t "Warning: Could not load HTTP dependencies: ~A~%" e)
      (format t "Install with: (ql:quickload '(:drakma :cl-json))~%")
      (format t "Will use mock responses only.~%"))))

;;; =============================================================================
;;; UTILITY FUNCTIONS FOR FIXING CORRUPT UNITS
;;; =============================================================================

(defun fix-nil-worth-values ()
  "Fix any units that have NIL WORTH values"
  (let ((fixed-count 0))
    (dolist (unit *units*)
      (when (and unit (null (worth unit)))
        (put unit 'worth 400)
        (incf fixed-count)
        (cprin1 40 "Fixed NIL WORTH for unit: " unit "~%")))
    (cprin1 15 "Fixed " fixed-count " units with NIL WORTH values~%")
    fixed-count))

(defun safe-worth (unit)
  "Get WORTH of unit, defaulting to 400 if NIL"
  (or (worth unit) 400))

(defun diagnose-worth-issues ()
  "Diagnose and report units with problematic WORTH values"
  (let ((nil-worth-units '())
        (invalid-worth-units '())
        (total-units 0))
    (dolist (unit *units*)
      (when unit
        (incf total-units)
        (let ((worth-val (worth unit)))
          (cond
            ((null worth-val)
             (push unit nil-worth-units))
            ((not (numberp worth-val))
             (push unit invalid-worth-units))
            ((<= worth-val 0)
             (push unit invalid-worth-units))))))
    (format t "~%=== WORTH Diagnosis ===~%")
    (format t "Total units: ~A~%" total-units)
    (format t "Units with NIL WORTH: ~A~%" (length nil-worth-units))
    (format t "Units with invalid WORTH: ~A~%" (length invalid-worth-units))
    (when nil-worth-units
      (format t "NIL WORTH units: ~A~%" (subseq nil-worth-units 0 (min 10 (length nil-worth-units)))))
    (when invalid-worth-units
      (format t "Invalid WORTH units: ~A~%" (subseq invalid-worth-units 0 (min 10 (length invalid-worth-units)))))
    (+ (length nil-worth-units) (length invalid-worth-units))))

;;; =============================================================================
;;; SHARED HEURISTIC VARIABLES
;;; =============================================================================

;; Declare variables that are defined in heuristics.lisp but needed here
(defvar *old-value*)
(defvar *new-value*)
(defvar *slot-to-change*)
(defvar *new-units*)
(defvar *creditors*)
(defvar *conjectures*)
(defvar *units*)
(defvar *deleted-units*)
(defvar *task-num*)
(defvar *task*)
(defvar *abort-task?*)

;; LLM-specific variables
(defvar *llm-generated-concepts* nil "List of concepts generated by LLM")
(defvar *llm-generated-slots* nil "List of slots generated by LLM")
(defvar *llm-suggested-rules* nil "List of rules suggested by LLM")

;;; =============================================================================
;;; LLM INFRASTRUCTURE (Fixed)
;;; =============================================================================

;;; LLM Provider Configuration
(defvar *llm-provider* :ollama
  "Current LLM provider. Supported: :gemini, :openai, :claude, :ollama")

(defvar *llm-api-key* nil
  "API key for the current LLM provider")

(defvar *llm-model* "qwen2.5:14b"
  "Model name for the current provider")

(defvar *llm-temperature* 0.7
  "Temperature setting for LLM responses")

(defvar *llm-max-tokens* 2048
  "Maximum tokens for LLM responses")

(defvar *llm-timeout* 30
  "Timeout for LLM API calls in seconds")

;;; LLM Provider Configurations
(defparameter *llm-providers*
  '((:gemini 
     :base-url "https://generativelanguage.googleapis.com/v1beta/models/"
     :headers (("Content-Type" . "application/json"))
     :auth-header "x-goog-api-key"
     :request-format :gemini)
    (:openai
     :base-url "https://api.openai.com/v1/chat/completions"
     :headers (("Content-Type" . "application/json"))
     :auth-header "Authorization"
     :auth-prefix "Bearer "
     :request-format :openai)
    (:claude
     :base-url "https://api.anthropic.com/v1/messages"
     :headers (("Content-Type" . "application/json")
               ("anthropic-version" . "2023-06-01"))
     :auth-header "x-api-key"
     :request-format :claude)
    (:ollama
     :base-url "http://localhost:11434/api/generate"
     :headers (("Content-Type" . "application/json"))
     :request-format :ollama)))

;;; =============================================================================
;;; LLM INTERFACE FUNCTIONS (Fixed)
;;; =============================================================================

(defun get-provider-config (provider)
  "Get configuration for the specified LLM provider"
  (cdr (assoc provider *llm-providers*)))

(defun escape-json-string (str)
  "Escape a string for JSON"
  (with-output-to-string (out)
    (loop for char across str do
      (case char
        (#\" (write-string "\\\"" out))
        (#\\ (write-string "\\\\" out))
        (#\Newline (write-string "\\n" out))
        (#\Return (write-string "\\r" out))
        (#\Tab (write-string "\\t" out))
        (otherwise (write-char char out))))))

(defun eurisko-llm-api-call (prompt &key provider model temperature max-tokens)
  "Make HTTP request to LLM API - fixed version with proper JSON escaping"
  (let* ((provider (or provider *llm-provider*))
         (model (or model *llm-model*))
         (config (get-provider-config provider))
         (base-url (getf config :base-url))
         (api-key *llm-api-key*))
    
    (handler-case
        (case provider
          (:gemini
           (if (and api-key (stringp api-key) (not (string= api-key "")))
               (let* ((json-string (format nil "{\"contents\":[{\"parts\":[{\"text\":\"~A\"}]}],\"generationConfig\":{\"temperature\":~A,\"maxOutputTokens\":~A}}" 
                                          (escape-json-string prompt)
                                          (or temperature *llm-temperature*)
                                          (or max-tokens *llm-max-tokens*)))
                      (full-url (format nil "~A~A:generateContent?key=~A" base-url model api-key)))
                 (multiple-value-bind (response status-code)
                     (drakma:http-request full-url
                                        :method :post
                                        :content-type "application/json"
                                        :content json-string
                                        :want-stream nil)
                   (if (= status-code 200)
                       (let ((response-string (if (stringp response)
                                                  response
                                                  (map 'string #'code-char response))))
                         (cl-json:decode-json-from-string response-string))
                       (format nil "API Error: Status ~A" status-code))))
               (format nil "Mock Gemini response - no API key")))
          
          (:ollama
           ;; Ollama doesn't need an API key - escape the prompt for JSON
           (let* ((json-string (format nil "{\"model\":\"~A\",\"prompt\":\"~A\",\"stream\":false,\"options\":{\"temperature\":~A}}" 
                                      model (escape-json-string prompt) (or temperature *llm-temperature*)))
                  (full-url base-url))
             (multiple-value-bind (response status-code)
                 (drakma:http-request full-url
                                    :method :post
                                    :content-type "application/json"
                                    :content json-string
                                    :want-stream nil)
               (if (= status-code 200)
                   (let ((response-string (if (stringp response)
                                              response
                                              (map 'string #'code-char response))))
                     (cl-json:decode-json-from-string response-string))
                   (format nil "Ollama Error: Status ~A" status-code)))))
          
          (:openai
           (format nil "OpenAI not implemented yet"))
          
          (otherwise
           (format nil "Provider ~A not implemented" provider)))
      (error (e)
        (format nil "Error calling LLM: ~A" e)))))

(defun extract-llm-response (response provider)
  "Extract text content from LLM response based on provider format"
  (cond
    ;; If it's already a string (mock response), return as-is
    ((stringp response) response)
    
    ;; Handle real API responses
    ((listp response)
     (case provider
       (:gemini
        ;; Navigate: CANDIDATES -> first item -> CONTENT -> PARTS -> first item -> TEXT
        (let* ((candidates (cdr (assoc :candidates response)))
               (first-candidate (first candidates))
               (content (cdr (assoc :content first-candidate)))
               (parts (cdr (assoc :parts content)))
               (first-part (first parts))
               (text (cdr (assoc :text first-part))))
          text))
       (:ollama
        ;; Ollama returns response in :RESPONSE field (keyword)
        (cdr (assoc :response response)))
       (:openai
        (let* ((choices (cdr (assoc :choices response)))
               (first-choice (first choices))
               (message (cdr (assoc :message first-choice)))
               (content (cdr (assoc :content message))))
          content))
       (:claude
        (let* ((content (cdr (assoc :content response)))
               (first-content (first content))
               (text (cdr (assoc :text first-content))))
          text))
       (otherwise
        (format nil "Unknown provider: ~A" provider))))
    
    ;; Fallback
    (t (format nil "~A" response))))

(defun llm-query (prompt &key provider model temperature max-tokens context)
  "High-level interface for LLM queries"
  (let* ((full-prompt (if context
                         (format nil "Context: ~A~%~%Query: ~A" context prompt)
                         prompt))
         (_ (cprin1 40 "Prompt: " full-prompt "~%"))
         (response (eurisko-llm-api-call full-prompt 
                                        :provider provider 
                                        :model model 
                                        :temperature temperature 
                                        :max-tokens max-tokens)))
    
    (when response
      (let ((text (extract-llm-response response (or provider *llm-provider*))))
        ;; Ensure we always return a string
        (unless (stringp text)
          (setf text (format nil "~A" text)))
        (cprin1 40 "Response: " text)
        text))))

;;; =============================================================================
;;; STRUCTURED LLM OUTPUT PARSERS
;;; =============================================================================

(defun parse-llm-concept-definition (response)
  "Parse LLM response into structured concept definition"
  (when (and response (stringp response))
    (let ((lines (split-string response #\Newline))
          (concept-def '()))
      (dolist (line lines)
        (let ((trimmed (string-trim '(#\Space #\Tab) line)))
          (cond
            ((search "NAME:" trimmed)
             (push (cons 'name (string-trim '(#\Space) (subseq trimmed 5))) concept-def))
            ((search "ISA:" trimmed)
             (push (cons 'isa (intern (string-upcase (string-trim '(#\Space) (subseq trimmed 4))))) concept-def))
            ((search "ENGLISH:" trimmed)
             (push (cons 'english (string-trim '(#\Space) (subseq trimmed 8))) concept-def))
            ((search "DOMAIN:" trimmed)
             (push (cons 'domain (intern (string-upcase (string-trim '(#\Space) (subseq trimmed 7))))) concept-def))
            ((search "WORTH:" trimmed)
             (let ((worth-str (string-trim '(#\Space) (subseq trimmed 6))))
               (push (cons 'worth (parse-integer worth-str :junk-allowed t)) concept-def))))))
      (when concept-def (nreverse concept-def)))))

(defun parse-llm-slot-suggestion (response)
  "Parse LLM response into structured slot suggestion"
  (when (and response (stringp response))
    (let ((lines (split-string response #\Newline))
          (slot-def '()))
      (dolist (line lines)
        (let ((trimmed (string-trim '(#\Space #\Tab) line)))
          (cond
            ((search "SLOT:" trimmed)
             (push (cons 'slot (intern (string-upcase (string-trim '(#\Space) (subseq trimmed 5))))) slot-def))
            ((search "VALUE:" trimmed)
             (push (cons 'value (string-trim '(#\Space) (subseq trimmed 6))) slot-def))
            ((search "REASON:" trimmed)
             (push (cons 'reason (string-trim '(#\Space) (subseq trimmed 7))) slot-def)))))
      (when slot-def (nreverse slot-def)))))

(defun parse-llm-rule (response)
  "Parse LLM response into structured rule"
  (when (and response (stringp response))
    (let ((if-pos (search "IF:" response))
          (then-pos (search "THEN:" response))
          (worth-pos (search "WORTH:" response)))
      (when (and if-pos then-pos)
        `((condition . ,(string-trim '(#\Space #\Newline) 
                                   (subseq response (+ if-pos 3) then-pos)))
          (action . ,(string-trim '(#\Space #\Newline)
                                (subseq response (+ then-pos 5) 
                                       (or worth-pos (length response)))))
          (worth . ,(when worth-pos
                     (parse-integer (string-trim '(#\Space #\Newline)
                                               (subseq response (+ worth-pos 6)))
                                   :junk-allowed t))))))))

(defun split-string (string delimiter)
  "Simple string splitting utility"
  (let ((result '())
        (start 0))
    (loop for pos = (position delimiter string :start start)
          do (push (subseq string start pos) result)
             (if pos
                 (setf start (1+ pos))
                 (return (nreverse result))))))

;;; =============================================================================
;;; SYMBOLIC INTEGRATION UTILITIES
;;; =============================================================================

(defvar *unit-failure-counts* (make-hash-table)
  "Track how many times each unit has failed operations")

(defun count-failures-for-unit (unit)
  "Count how many times a unit has failed operations"
  (gethash unit *unit-failure-counts* 0))

(defun record-failure-for-unit (unit)
  "Record a failure for a unit"
  (setf (gethash unit *unit-failure-counts*)
        (1+ (gethash unit *unit-failure-counts* 0))))

(defun implement-llm-rule (rule-def)
  "Convert an LLM-generated rule into a working EURISKO heuristic"
  (when rule-def
    (let* ((rule-name (cdr (assoc 'name rule-def)))
           (condition-text (cdr (assoc 'condition rule-def)))
           (action-text (cdr (assoc 'action rule-def)))
           (worth (or (cdr (assoc 'worth rule-def)) 400)))
      
      (when (and rule-name condition-text action-text)
        (cprin1 40 "Implementing LLM rule: " rule-name "~%")
        
        ;; For now, create a simple avoidance heuristic
        ;; In a full implementation, you'd parse condition-text into actual Lisp predicates
        (eval 
         `(defheuristic ,rule-name
            isa (heuristic op anything)
            english ,(format nil "LLM-Generated: ~A" action-text)
            if-potentially-relevant (lambda (f)
                                      ;; Simple heuristic: avoid if unit has failed before
                                      (> (count-failures-for-unit f) 1))
            worth ,worth
            abbrev ,(format nil "LLM: ~A" (subseq action-text 0 (min 50 (length action-text))))
            then-compute (lambda (f)
                           (cprin1 15 "LLM rule " ',rule-name " preventing operation on " f "~%")
                           nil) ; Return nil to prevent the operation
            arity 1))
        
        ;; Register the new heuristic
        (when (fboundp 'union-prop)
          (union-prop 'heuristic 'examples rule-name))
        
        (cprin1 15 "Successfully implemented heuristic: " rule-name "~%")
        t))))

(defun create-concept-from-llm (concept-def)
  "Create a EURISKO concept from LLM-generated definition"
  (when concept-def
    (let* ((name-str (cdr (assoc 'name concept-def)))
           (concept-name (when name-str (intern (string-upcase name-str)))))
      (when concept-name
        (cprin1 40 "Creating LLM-generated concept: " concept-name "~%")
        ;; Create the unit
        (create-unit concept-name concept-name)
        ;; Set properties from LLM definition
        (dolist (prop concept-def)
          (case (car prop)
            (isa 
             ;; Ensure ISA is always a list
             (let ((isa-value (cdr prop)))
               (put concept-name 'isa 
                    (if (listp isa-value) isa-value (list isa-value)))))
            (english (put concept-name 'english (cdr prop)))
            (domain 
             ;; Ensure DOMAIN is always a list  
             (let ((domain-value (cdr prop)))
               (put concept-name 'domain
                    (if (listp domain-value) domain-value (list domain-value)))))
            (worth 
             ;; Ensure WORTH is always a valid number
             (let ((worth-value (cdr prop)))
               (put concept-name 'worth 
                    (if (and worth-value (numberp worth-value) (> worth-value 0))
                        worth-value
                        400)))))) ; Default worth if invalid
        ;; Ensure all LLM concepts have a WORTH value
        (unless (and (worth concept-name) (numberp (worth concept-name)) (> (worth concept-name) 0))
          (put concept-name 'worth 400))
        ;; Mark as LLM-generated
        (put concept-name 'creditors '(llm-generated))
        (push concept-name *llm-generated-concepts*)
        concept-name))))

(defun add-slot-from-llm (unit slot-def)
  "Add a slot to a unit based on LLM suggestion - enhanced with WORTH validation"
  (when (and unit slot-def)
    (let ((slot-name (cdr (assoc 'slot slot-def)))
          (slot-value-text (cdr (assoc 'value slot-def)))
          (reason (cdr (assoc 'reason slot-def))))
      (when (and slot-name slot-value-text)
        (cprin1 40 "Adding LLM-suggested slot " slot-name " to " unit "~%")
        
        ;; Convert text to appropriate EURISKO value
        (let ((slot-value (convert-text-to-slot-value slot-value-text slot-name)))
          (when slot-value
            (put unit slot-name slot-value)
            (when reason
              (put unit (intern (format nil "~A-REASON" slot-name)) reason))
            
            ;; Special handling: if we just set WORTH to something invalid, fix it
            (when (and (eq slot-name 'worth) (not (and (numberp slot-value) (> slot-value 0))))
              (put unit 'worth 400)
              (cprin1 40 "Corrected invalid WORTH value for " unit " to 400~%"))
            
            ;; Ensure unit always has a valid WORTH
            (unless (and (worth unit) (numberp (worth unit)) (> (worth unit) 0))
              (put unit 'worth 400)
              (cprin1 40 "Ensured " unit " has valid WORTH value~%"))
            
            (push (list unit slot-name slot-value) *llm-generated-slots*)
            (cprin1 40 "Successfully added slot " slot-name " with value " slot-value "~%")
            t))))))

(defun convert-text-to-slot-value (text slot-name)
  "Convert LLM text to appropriate EURISKO slot value"
  (when (stringp text)
    (let ((trimmed (string-trim '(#\Space #\Tab #\Newline) text)))
      (cond
        ;; Empty string
        ((= (length trimmed) 0) nil)
        
        ;; For WORTH slot, ensure we get a number
        ((let ((slot-name-str (cond ((symbolp slot-name) (symbol-name slot-name))
                                   ((stringp slot-name) (string-upcase slot-name))
                                   (t (format nil "~A" slot-name)))))
           (string= slot-name-str "WORTH"))
         (let ((parsed-number (parse-integer trimmed :junk-allowed t)))
           (if (and parsed-number (> parsed-number 0))
               parsed-number
               (progn
                 (cprin1 40 "Warning: Invalid WORTH value '" trimmed "', defaulting to 400~%")
                 400))))
        
        ;; Special handling for slots that EURISKO expects as lists
        ((let ((slot-name-str (cond ((symbolp slot-name) (symbol-name slot-name))
                                   ((stringp slot-name) (string-upcase slot-name))
                                   (t (format nil "~A" slot-name)))))
           (some (lambda (expected-slot) (string= slot-name-str expected-slot))
                 '("DOMAIN" "ISA" "EXAMPLES" "SPECIALIZATIONS" "GENERALIZATIONS" 
                   "APPLICS-OF" "APPLICS-TO" "APPLICS-WITH" "SUPERIORS" "SUBORDINATES")))
         ;; Convert to a list containing the symbol
         (let ((symbol-value (if (and (> (length trimmed) 0)
                                     (alpha-char-p (char trimmed 0))
                                     (every (lambda (c) (or (alphanumericp c) (char= c #\-))) trimmed)
                                     (< (length trimmed) 30))
                               (intern (string-upcase trimmed))
                               trimmed)))
           (list symbol-value)))
        
        ;; If it looks like a pure number, parse it
        ((every (lambda (c) (or (digit-char-p c) (char= c #\.) (char= c #\-))) trimmed)
         (or (parse-float trimmed :junk-allowed t)
             (parse-integer trimmed :junk-allowed t)
             trimmed))
        
        ;; If it's trying to be a list or function, be very careful
        ((and (> (length trimmed) 0)
              (or (char= (char trimmed 0) #\()
                  (search "lambda" trimmed)
                  (search "IF " trimmed)
                  (search "THEN " trimmed)))
         ;; For now, don't try to evaluate LLM-generated code
         ;; Store as text with a warning
         (cprin1 40 "Warning: LLM generated code-like text for " slot-name ", storing as description~%")
         (format nil "LLM-Description: ~A" trimmed))
        
        ;; If it looks like a simple concept name, try to intern it
        ((and (> (length trimmed) 0)
              (alpha-char-p (char trimmed 0))
              (every (lambda (c) (or (alphanumericp c) (char= c #\-))) trimmed)
              (< (length trimmed) 30)) ; Reasonable concept name length
         (intern (string-upcase trimmed)))
        
        ;; Default: store as text for safety
        (t trimmed)))))

(defun parse-float (string &key (junk-allowed nil))
  "Simple float parser"
  (handler-case
      (let ((*read-eval* nil))
        (read-from-string string nil nil))
    (error () 
      (if junk-allowed nil (error "Not a valid float")))))

(defun create-avoidance-rule-from-llm (rule-def context)
  "Create an avoidance heuristic from LLM-generated rule"
  (when rule-def
    (let* ((condition (cdr (assoc 'condition rule-def)))
           (action (cdr (assoc 'action rule-def)))
           (worth (or (cdr (assoc 'worth rule-def)) 300))
           (rule-name (intern (format nil "H-LLM-AVOID-~A" (length *llm-suggested-rules*)))))
      (when (and condition action)
        (cprin1 40 "Creating LLM-generated avoidance rule: " rule-name "~%")
        ;; Store the rule for potential implementation
        (push `((name . ,rule-name)
                (condition . ,condition)
                (action . ,action)
                (worth . ,worth)
                (context . ,context)) *llm-suggested-rules*)
        rule-name))))


;;; =============================================================================
;;; MATHEMATICAL CONCEPT DISCOVERY WITH LLM
;;; =============================================================================

(defheuristic h30-llm-mathematical-explorer
  isa (heuristic op anything)
  english "IF we have interesting mathematical structures, THEN use LLM to suggest extensions and generalizations"
  if-potentially-relevant (lambda (f)
                            (and *llm-api-key*
                                 (or (memb 'math-concept (isa f))
                                     (memb 'math-op (isa f))
                                     (memb 'structure (generalizations f))
                                     (memb 'set-op (isa f))
                                     (memb 'num-op (isa f)))))
  worth 800
  abbrev "LLM-guided mathematical concept exploration"
  then-compute (lambda (f)
                 (cprin1 40 "H30: Exploring mathematical extensions of " f "~%")
                 
                 ;; Find related mathematical concepts from EURISKO's knowledge
                 (let* ((math-concepts (remove-if-not 
                                       (lambda (u)
                                         (and u (symbolp u)
                                              (english u)
                                              (isa u)
                                              (or (memb 'math-concept (isa u))
                                                  (memb 'math-op (isa u))
                                                  (memb 'structure (generalizations u))
                                                  (memb 'prime-num (isa u))
                                                  (memb 'set (generalizations u)))
                                              (> (safe-worth u) 400)))
                                       *units*))
                        
                        ;; Select 3-4 good examples including the current focus
                        (selected-concepts (cons f (subseq math-concepts 0 (min 3 (length math-concepts)))))
                        
                        ;; Build context from EURISKO's actual mathematical knowledge
                        (math-context 
                         (format nil "EURISKO's Mathematical Knowledge:~%~{~A~%~}"
                                (mapcar (lambda (c)
                                         (format nil "- ~A: ~A [ISA: ~A, Domain: ~A, Worth: ~A]"
                                                c
                                                (or (english c) (abbrev c) "Mathematical structure")
                                                (or (first (isa c)) "concept")
                                                (or (first (domain c)) "mathematics")
                                                (safe-worth c)))
                                       selected-concepts)))
                        
                        (prompt (format nil "~A

You are helping EURISKO discover new mathematical concepts. Based on the mathematical structures above, suggest a NEW concept that would extend or generalize these ideas.

Focus on:
- Set theory and structure operations (like the ones EURISKO knows: set-union, set-intersect, bag-operations)
- Number theory concepts (building on prime-num, even-num, perfect squares)
- Algebraic structures and operations
- Geometric or topological concepts

Generate exactly this format:
NAME: [short mathematical name]
ISA: [parent concept from EURISKO's hierarchy]
ENGLISH: [precise mathematical definition]
DOMAIN: [mathematical domain]
WORTH: [estimated worth 400-900]

Make it mathematically rigorous and useful for EURISKO's discovery process!"
                                       math-context))
                        
                        (response (llm-query prompt :temperature 0.7)))
                   
                   (when response
                     (let ((concept-def (parse-llm-concept-definition response)))
                       (if concept-def
                           (let ((new-concept (create-concept-from-llm concept-def)))
                             (when new-concept
                               (cprin1 15 "H30: Created mathematical concept " new-concept " inspired by " f "~%")
                               (add-task-results 'llm-mathematical-concept new-concept)
                               t))
                           (progn
                             (cprin1 40 "H30: Failed to parse mathematical concept definition~%")
                             nil))))))
  arity 1)

(defheuristic h31-llm-operation-synthesizer
  isa (heuristic op anything)
  english "IF we're working with mathematical operations, THEN use LLM to suggest new operations"
  if-potentially-relevant (lambda (f)
                            (and *llm-api-key*
                                 (or (memb 'set-op (isa f))
                                     (memb 'num-op (isa f))
                                     (memb 'struc-op (isa f))
                                     (memb 'list-op (isa f))
                                     (memb 'bag-op (isa f)))))
  worth 750
  abbrev "LLM-guided mathematical operation synthesis"
  then-compute (lambda (f)
                 (cprin1 40 "H31: Synthesizing operations related to " f "~%")
                 
                 ;; Find operations in the same category
                 (let* ((operation-type (cond 
                                        ((memb 'set-op (isa f)) 'set-op)
                                        ((memb 'num-op (isa f)) 'num-op)
                                        ((memb 'struc-op (isa f)) 'struc-op)
                                        ((memb 'list-op (isa f)) 'list-op)
                                        ((memb 'bag-op (isa f)) 'bag-op)
                                        (t 'math-op)))
                        
                        ;; Get examples of this operation type
                        (related-ops (remove-if-not 
                                     (lambda (u)
                                       (and u (memb operation-type (isa u))
                                            (english u)
                                            (arity u)
                                            (domain u)
                                            (range u)))
                                     (examples operation-type)))
                        
                        (op-examples (subseq related-ops 0 (min 4 (length related-ops))))
                        
                        (context (format nil "EURISKO's ~A Operations:~%~{~A~%~}"
                                        operation-type
                                        (mapcar (lambda (op)
                                                 (format nil "- ~A: ~A [Arity: ~A, Domain: ~A -> Range: ~A]"
                                                        op
                                                        (english op)
                                                        (arity op)
                                                        (domain op)
                                                        (range op)))
                                               op-examples)))
                        
                        (prompt (format nil "~A

Suggest a NEW mathematical operation that complements these existing ~A operations.

The operation should:
1. Work with the same mathematical structures (sets, numbers, structures, etc.)
2. Have clear mathematical meaning and utility
3. Fill a gap in EURISKO's current operation set
4. Be implementable with a concrete algorithm

Generate exactly this format:
NAME: [operation name]
ISA: [single parent concept like ~A or MATH-OP]
ENGLISH: [precise mathematical description of what the operation does]
ARITY: [number of arguments]
DOMAIN: [simple input types like NNUMBER or SET]
RANGE: [simple output type like NNUMBER or SET]
WORTH: [estimated worth 400-800]

Be mathematically precise and use simple concept names!"
                                       context operation-type operation-type))
                        
                        (response (llm-query prompt :temperature 0.6)))
                   
                   (when response
                     (let ((op-def (parse-llm-operation-definition response)))
                       (if op-def
                           (let ((new-op (create-operation-from-llm op-def)))
                             (when new-op
                               (cprin1 15 "H31: Created operation " new-op " in " operation-type " category~%")
                               (add-task-results 'llm-mathematical-operation new-op)
                               t))
                           (progn
                             (cprin1 40 "H31: Failed to parse operation definition~%")
                             nil))))))
  arity 1)

(defheuristic h32-llm-structure-analyzer
  isa (heuristic op anything)
  english "IF we discover interesting mathematical structures, THEN use LLM to analyze their properties"
  if-potentially-relevant (lambda (f)
                            (and *llm-api-key*
                                 (or (memb 'structure (generalizations f))
                                     (memb 'set (generalizations f))
                                     (memb 'bag (generalizations f))
                                     (memb 'list (generalizations f)))
                                 (specializations f)
                                 (> (length (specializations f)) 1)))
  worth 700
  abbrev "LLM-guided mathematical structure analysis"
  then-compute (lambda (f)
                 (cprin1 40 "H32: Analyzing mathematical structure " f "~%")
                 
                 (let* ((struct-info (format nil "Structure: ~A
Description: ~A
Generalizations: ~A
Specializations: ~A
Related Operations: ~A"
                                            f
                                            (english f)
                                            (generalizations f)
                                            (specializations f)
                                            (remove-if-not (lambda (op)
                                                            (or (memb f (domain op))
                                                                (memb f (range op))))
                                                          *units*)))
                        
                        (prompt (format nil "~A

Analyze this mathematical structure and suggest either:
1. A missing property/slot that would better characterize this structure
2. A mathematical relationship between this structure and its specializations
3. A structural invariant or important mathematical property

Focus on mathematical concepts like:
- Algebraic properties (associativity, commutativity, etc.)
- Structural properties (finiteness, boundedness, etc.)  
- Relationships between generalizations and specializations
- Important mathematical theorems or principles

Generate exactly this format:
ANALYSIS_TYPE: [PROPERTY, RELATIONSHIP, or INVARIANT]
SLOT: [slot name for the property]
VALUE: [mathematical description or formal property]
REASON: [mathematical justification]
WORTH: [estimated worth 300-700]"
                                       struct-info))
                        
                        (response (llm-query prompt :temperature 0.5)))
                   
                   (when response
                     (let ((analysis (parse-llm-structure-analysis response)))
                       (if (and analysis (add-slot-from-llm f analysis))
                           (progn
                             (cprin1 15 "H32: Added mathematical property to " f "~%")
                             (add-task-results 'llm-structure-analysis analysis)
                             t)
                           (progn
                             (cprin1 40 "H32: Failed to apply structural analysis~%")
                             nil))))))
  arity 1)

(defheuristic h33-llm-theorem-suggester
  isa (heuristic op anything)
  english "IF we have related mathematical concepts with good examples, THEN suggest mathematical conjectures"
  if-potentially-relevant (lambda (f)
                            (and *llm-api-key*
                                 (memb 'math-concept (isa f))
                                 (examples f)
                                 (> (length (examples f)) 2)
                                 (generalizations f)
                                 (> (safe-worth f) 600)))
  worth 650
  abbrev "LLM-guided mathematical conjecture generation"
  then-compute (lambda (f)
                 (cprin1 40 "H33: Generating mathematical conjectures about " f "~%")
                 
                 (let* ((concept-info (format nil "Mathematical Concept: ~A
Description: ~A  
Examples: ~A
Generalizations: ~A
Specializations: ~A
Worth: ~A"
                                             f
                                             (english f)
                                             (subseq (examples f) 0 (min 5 (length (examples f))))
                                             (generalizations f)
                                             (specializations f)
                                             (safe-worth f)))
                        
                        (prompt (format nil "~A

Based on this mathematical concept and its examples, suggest a mathematical conjecture or theorem that EURISKO could explore.

The conjecture should:
1. Be testable using EURISKO's existing operations
2. Relate to the examples and mathematical structure shown
3. Be mathematically interesting and non-trivial
4. Connect this concept to other mathematical areas

Generate exactly this format:
CONJECTURE: [precise mathematical statement]
DOMAIN: [what mathematical objects this applies to]
TESTABLE_WITH: [EURISKO operations that could verify this]
MATHEMATICAL_SIGNIFICANCE: [why this matters mathematically]
WORTH: [estimated worth 300-800]

Be precise and mathematically rigorous!"
                                       concept-info))
                        
                        (response (llm-query prompt :temperature 0.6)))
                   
                   (when response
                     (let ((conjecture (parse-llm-conjecture response)))
                       (if conjecture
                           (let ((new-conjecture (create-conjecture-from-llm conjecture f)))
                             (when new-conjecture
                               (cprin1 15 "H33: Generated mathematical conjecture about " f "~%")
                               (add-task-results 'llm-mathematical-conjecture new-conjecture)
                               t))
                           (progn
                             (cprin1 40 "H33: Failed to parse mathematical conjecture~%")
                             nil))))))
  arity 1)

;;; =============================================================================
;;; ENHANCED PARSING FUNCTIONS FOR MATHEMATICAL CONTENT
;;; =============================================================================

(defun parse-llm-operation-definition (response)
  "Parse LLM response into operation definition"
  (when (and response (stringp response))
    (let ((lines (split-string response #\Newline))
          (op-def '()))
      (dolist (line lines)
        (let ((trimmed (string-trim '(#\Space #\Tab) line)))
          (cond
            ((search "NAME:" trimmed)
             (push (cons 'name (string-trim '(#\Space) (subseq trimmed 5))) op-def))
            ((search "ISA:" trimmed)
             (let ((isa-text (string-trim '(#\Space) (subseq trimmed 4))))
               ;; Handle simple case - just read the first symbol
               (push (cons 'isa (list (intern (string-upcase 
                                              (first (split-string isa-text #\Space)))))) op-def)))
            ((search "ENGLISH:" trimmed)
             (push (cons 'english (string-trim '(#\Space) (subseq trimmed 8))) op-def))
            ((search "ARITY:" trimmed)
             (push (cons 'arity (parse-integer (string-trim '(#\Space) (subseq trimmed 6)) :junk-allowed t)) op-def))
            ((search "DOMAIN:" trimmed)
             (let ((domain-text (string-trim '(#\Space) (subseq trimmed 7))))
               ;; Handle simple domain like "NNUMBER" or "SET"
               (push (cons 'domain (list (intern (string-upcase domain-text)))) op-def)))
            ((search "RANGE:" trimmed)
             (let ((range-text (string-trim '(#\Space) (subseq trimmed 6))))
               ;; Handle simple range like "NNUMBER" or "SET"  
               (push (cons 'range (list (intern (string-upcase range-text)))) op-def)))
            ((search "WORTH:" trimmed)
             (push (cons 'worth (parse-integer (string-trim '(#\Space) (subseq trimmed 6)) :junk-allowed t)) op-def)))))
      (when op-def (nreverse op-def)))))

(defun parse-llm-structure-analysis (response)
  "Parse LLM structural analysis response"
  (when (and response (stringp response))
    (let ((lines (split-string response #\Newline))
          (analysis '()))
      (dolist (line lines)
        (let ((trimmed (string-trim '(#\Space #\Tab) line)))
          (cond
            ((search "ANALYSIS_TYPE:" trimmed)
             (push (cons 'analysis-type (string-trim '(#\Space) (subseq trimmed 14))) analysis))
            ((search "SLOT:" trimmed)
             (push (cons 'slot (intern (string-upcase (string-trim '(#\Space) (subseq trimmed 5))))) analysis))
            ((search "VALUE:" trimmed)
             (push (cons 'value (string-trim '(#\Space) (subseq trimmed 6))) analysis))
            ((search "REASON:" trimmed)
             (push (cons 'reason (string-trim '(#\Space) (subseq trimmed 7))) analysis))
            ((search "WORTH:" trimmed)
             (push (cons 'worth (parse-integer (string-trim '(#\Space) (subseq trimmed 6)) :junk-allowed t)) analysis)))))
      (when analysis (nreverse analysis)))))

(defun parse-llm-conjecture (response)
  "Parse LLM conjecture response"
  (when (and response (stringp response))
    (let ((lines (split-string response #\Newline))
          (conjecture '()))
      (dolist (line lines)
        (let ((trimmed (string-trim '(#\Space #\Tab) line)))
          (cond
            ((search "CONJECTURE:" trimmed)
             (push (cons 'conjecture (string-trim '(#\Space) (subseq trimmed 11))) conjecture))
            ((search "DOMAIN:" trimmed)
             (push (cons 'domain (string-trim '(#\Space) (subseq trimmed 7))) conjecture))
            ((search "TESTABLE_WITH:" trimmed)
             (push (cons 'testable-with (string-trim '(#\Space) (subseq trimmed 14))) conjecture))
            ((search "MATHEMATICAL_SIGNIFICANCE:" trimmed)
             (push (cons 'significance (string-trim '(#\Space) (subseq trimmed 26))) conjecture))
            ((search "WORTH:" trimmed)
             (push (cons 'worth (parse-integer (string-trim '(#\Space) (subseq trimmed 6)) :junk-allowed t)) conjecture)))))
      (when conjecture (nreverse conjecture)))))

(defun create-operation-from-llm (op-def)
  "Create a EURISKO operation from LLM definition"
  (when op-def
    (let* ((name-str (cdr (assoc 'name op-def)))
           (op-name (when name-str (intern (string-upcase name-str)))))
      (when op-name
        (cprin1 40 "Creating LLM-generated operation: " op-name "~%")
        (create-unit op-name op-name)
        
        ;; Set operation properties
        (dolist (prop op-def)
          (case (car prop)
            (isa (put op-name 'isa (cdr prop)))
            (english (put op-name 'english (cdr prop)))
            (arity (put op-name 'arity (cdr prop)))
            (domain (put op-name 'domain (cdr prop)))
            (range (put op-name 'range (cdr prop)))
            (worth (put op-name 'worth (or (cdr prop) 400)))))
        
        ;; Ensure valid WORTH
        (unless (and (worth op-name) (numberp (worth op-name)) (> (worth op-name) 0))
          (put op-name 'worth 400))
        
        ;; Mark as LLM-generated and eliminate applics
        (put op-name 'creditors '(llm-generated))
        (put op-name 'elim-slots '(applics))
        
        op-name))))

(defun create-conjecture-from-llm (conjecture-def about-concept)
  "Create a EURISKO conjecture from LLM definition"
  (when conjecture-def
    (let* ((conjecture-text (cdr (assoc 'conjecture conjecture-def)))
           (conjecture-name (intern (format nil "CONJEC-LLM-~A" (length *llm-suggested-rules*)))))
      (when conjecture-text
        (cprin1 40 "Creating LLM-generated conjecture: " conjecture-name "~%")
        (create-unit conjecture-name conjecture-name)
        
        (put conjecture-name 'isa '(conjecture))
        (put conjecture-name 'english conjecture-text)
        (put conjecture-name 'conjecture-about about-concept)
        (put conjecture-name 'worth (or (cdr (assoc 'worth conjecture-def)) 400))
        (put conjecture-name 'creditors '(llm-generated))
        
        ;; Add to conjectures list if it exists
        (when (fboundp 'union-prop)
          (union-prop about-concept 'conjectures conjecture-name))
        
        conjecture-name))))

;;; =============================================================================
;;; MATHEMATICAL QUALITY FILTERS
;;; =============================================================================

(defun is-mathematical-concept (unit)
  "Check if unit represents actual mathematics, not meta-reasoning"
  (when (and unit (symbolp unit))
    (let ((isa-list (isa unit))
          (english-desc (english unit)))
      (and isa-list
           english-desc
           (stringp english-desc)
           ;; Must be mathematical
           (or (memb 'math-concept isa-list)
               (memb 'math-op isa-list)
               (memb 'math-obj isa-list)
               (memb 'structure (generalizations unit))
               (memb 'prime-num isa-list)
               (memb 'set isa-list))
           ;; Not meta-reasoning about EURISKO
           (not (search "Specializations of H" english-desc))
           (not (search "% are losers" english-desc))
           (not (search "heuristic" english-desc))))))

;;; =============================================================================
;;; INITIALIZATION
;;; =============================================================================

(defun register-mathematical-llm-heuristics ()
  "Register the redesigned mathematical LLM heuristics"
  (let ((math-heuristics '(h30-llm-mathematical-explorer
                          h31-llm-operation-synthesizer
                          h32-llm-structure-analyzer
                          h33-llm-theorem-suggester)))
    
    (when (fboundp 'union-prop)
      (dolist (h math-heuristics)
        (union-prop 'heuristic 'examples h)))
    
    (format t "Registered ~A mathematical LLM heuristics~%" (length math-heuristics))))

(defun initialize-mathematical-llm-system ()
  "Initialize the redesigned mathematical LLM system"
  (cprin1 13 "~%Initializing Mathematical LLM Discovery System...~%")
  (cprin1 13 "Heuristics: H30-H33 (Mathematical exploration, operation synthesis, structure analysis, theorem suggestion)~%")
  (cprin1 13 "Designed to work with EURISKO's actual mathematical knowledge~%")
  (register-mathematical-llm-heuristics))

;;; =============================================================================
;;; LLM CONFIGURATION AND UTILITIES
;;; =============================================================================

(defun configure-llm (provider &key api-key model temperature max-tokens)
  "Configure LLM settings"
  (setf *llm-provider* provider)
  ;; Only set API key if provided - Ollama doesn't need one
  (when api-key (setf *llm-api-key* api-key))
  (when model (setf *llm-model* model))
  (when temperature (setf *llm-temperature* temperature))
  (when max-tokens (setf *llm-max-tokens* max-tokens))
  (cprin1 13 "Configured LLM: " provider " with model " *llm-model* "~%"))

(defun llm-status ()
  "Display current LLM configuration status"
  (format t "~%LLM Status:~%")
  (format t "Provider: ~A~%" *llm-provider*)
  (format t "Model: ~A~%" *llm-model*)
  (format t "API Key: ~A~%" (if (and *llm-api-key* (not (string= *llm-api-key* ""))) 
                                "Set" 
                                "Not set"))
  (format t "Temperature: ~A~%" *llm-temperature*)
  (format t "Max Tokens: ~A~%" *llm-max-tokens*)
  (format t "Generated Concepts: ~A~%" (length *llm-generated-concepts*))
  (format t "Generated Slots: ~A~%" (length *llm-generated-slots*))
  (format t "Suggested Rules: ~A~%" (length *llm-suggested-rules*)))

(defun reset-llm-data ()
  "Reset LLM-generated data"
  (setf *llm-generated-concepts* nil
        *llm-generated-slots* nil
        *llm-suggested-rules* nil)
  (cprin1 13 "Reset LLM-generated data~%"))

(defun show-llm-insights ()
  "Display insights generated by LLM heuristics"
  (format t "~%=== LLM-Generated Insights ===~%")
  (format t "Concepts: ~A~%" *llm-generated-concepts*)
  (format t "Slots: ~A~%" *llm-generated-slots*)
  (format t "Rules: ~A~%" *llm-suggested-rules*))

;; Auto-initialize when loaded
(initialize-mathematical-llm-system)
